name: finme_chanlun_app
description: Finme Quant Chanlun market dashboard.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  shared_preferences: any

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
